os:
  - linux

language: php

php:
  - '7.2'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install

script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/assets/js/modules/*
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

  after_success:
    - travis_retry php vendor/bin/php-coveralls
    # or enable logging
    - travis_retry php vendor/bin/php-coveralls -v


  notifications:
    slack:
      on_success: never
      on_fail: never
    email:
      - bsmrrachel@gmail.com
